services:
  web:
    build: .
    ports:
      - "8080:80"
    environment:
      SQL_SERVER: "mysql"
      SQL_USERNAME: "root"
      SQL_PASSWORD: "secret"
      SQL_DB: "lab"
      VERSION: 3
    depends_on:
      mysql:
        condition: service_healthy
  mysql:
    image: "mysql:latest"
    expose:
      - "3306"
    environment:
      MYSQL_ROOT_PASSWORD: "secret"
      MYSQL_DATABASE: "lab"
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
