services:
  web:
    build: .
    ports:
      - "8080:80"
    environment:
      SQL_SERVER: "mysql"
      SQL_USERNAME: "root"
      SQL_PASSWORD: "secret"
      SQL_DB: "lab"
      VERSION: 3
  mysql:
    image: "mysql:latest"
    expose:
      - "3306"
    environment:
      MYSQL_ROOT_PASSWORD: "secret"
      MYSQL_DATABASE: "lab"